# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Install Python 3.8'
- script: pip install checkov
  displayName: 'Install Checkov'
- script: checkov -d "terraform/alicloud" --bc-api-key "2756b01-c350-4683-a0d7-cbb241dc86fc::SflOUWFJvXX1bPYbv7pNdF8RTIY=" --repo-id "DayoSE/terragoat"
  displayName: 'Scan with Prisma Cloud'
  env:
    PRISMA_API_URL: 'https://api.prismacloud.io'
