# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Install Python 3.8'
- script: pip install checkov
  displayName: 'Install Checkov'
- script: checkov -d . --bc-api-key "81c18ce2-88a2-4666-ada0-f4df626dd6d1::kF7n1onO88MXOwxXb82moluHCVg=" --repo-id "DayoSE/terragoat" 
  displayName: 'Scan with Prisma Cloud'
  env:
    PRISMA_API_URL: 'https://api.prismacloud.io'